apiVersion: v1
kind: Service
metadata:
  name: coo-svc
spec:
  type: NodePort
  selector:
    app: coo
  ports:
      # デフォルトでは利便性のため、 `targetPort` は `port` と同じ値にセットされます。
    - port: 8081
      targetPort: 8081
      # 省略可能なフィールド
      # デフォルトでは利便性のため、Kubernetesコントロールプレーンはある範囲から1つポートを割り当てます(デフォルト値の範囲:30000-32767)
      nodePort: 30000
